name: ostocare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_auth_web: ^5.14.1
  cloud_firestore_web: ^4.4.5
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.8
  firebase_core_web: ^2.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logoostocare.png
    - assets/homepageimg2.png
    - assets/homepageimg3.png
    - images/harcourts.png
    - images/healthguard.png
    - images/union_chemist.png
    - images/location.png
    - images/catalog.png
    - images/coloplast.png
    - images/hollister.png
    - images/surgi.png
    - images/colo1.png
    - images/colo2.png
    - images/colo3.png
    - images/colo4.png
    - images/colo5.png
    - images/colo6.png
    - images/colo7.png
    - images/colo8.png
    - images/colo9.png
    - images/colo10.png
    - images/colo11.png
    - images/colo12.png
    - images/hollister1.png
    - images/hollister2.png
    - images/surgi1.png
    - images/surgi2.png
    - images/surgi3.png
    - images/surgi4.png
